name: dogan-webui

services:
  dogan-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://dogan-api.xaigrok.ir/dogan/api/v1}
    image: ${WEB_IMAGE_TAG:-dogan-webui:latest}
    container_name: dogan-webui
    expose:
      - "80"
    ports:
      - target: 80
        published: ${WEB_PUBLISH_PORT-8082}
        protocol: tcp
    volumes:
      - dogan-webui-vol:/data
    networks:
      - t3-net
    restart: unless-stopped

networks:
  t3-net:
    name: ${DOCKER_NETWORK:-t3-net}
    external: true

volumes:
  dogan-webui-vol:
    name: dogan-webui-vol
